### ISSUE TITLE
Add support for angular 7

### ISSUE THREAD

**Issue by FeiVincent** [dominique-mueller/angular-notifier#114] opened 2018-11-20 03:53 UTC

**Comment by JoshuaNitschke** [comment] 2019-01-08 01:40
@witek1902 

FYI I am using this in an Angular 7 app (that started out as a 6) and it seems to work fine, although I do get an NPM install warning.

npm WARN angular-notifier@4.1.1 requires a peer of @angular/common@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/core@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by danner26** [comment] 2019-03-04 14:32
If we could just get the deps updated it should work fine I believe.

**Comment by vajnorcan** [comment] 2019-03-06 23:18
it doesn't work for me. any updates? (in the meantime I'll try to go through the source and see what the issue is)

**Comment by WojciechSlyp** [comment] 2019-05-16 15:19
Same here.

**Comment by elimin8r** [comment] 2019-06-04 14:32
well i guess we should change this to "support for angular 8" lol

**Comment by danner26** [comment] 2019-06-10 11:58
Agreed

**Comment by dominique-mueller** [comment] 2019-10-20 14:33
Fixed by #134, released as `5.0.0`. Also note that #139 adds support for Angular 8, released as `6.0.0`. Enjoy!

**Closed by dominique-mueller** 2019-10-20 14:33 UTC
Labels: BREAKING CHANGE, type: compatibility
