### ISSUE TITLE
Support for the html content

### ISSUE THREAD

**Issue by vajnorcan** [dominique-mueller/angular-notifier#81] opened 2018-06-07 23:14 UTC
I think this would be a duplicate of one of the issues below, but is there any chance the component would be enhanced to support ng-content in the template so we could provide our own html content (images etc) ?
Thanks for all your work

**Comment by dominique-mueller** [comment] 2018-06-22 10:54
Duplicate of https://github.com/dominique-mueller/angular-notifier/issues/37. It's a great idea, I just don't have the time right now :)

**Closed by dominique-mueller** 2018-06-22 10:54 UTC
Labels: duplicate
